version: 1.0.{build}
image: Visual Studio 2022
platform: Any CPU
configuration: Release
environment:
  mod_net_framework: net461
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - ps: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n BepInEx
  - ps: nuget restore
after_build:
  - cmd: 7z a binaries-%APPVEYOR_BUILD_VERSION%.zip Meta\bin\%Configuration%\%mod_net_framework%\LumineInCradle.*
artifacts:
  - path: binaries-$(APPVEYOR_BUILD_VERSION).zip
    name: binaries
deploy:
  - provider: GitHub
    artifact: binaries
    release: binaries v$(APPVEYOR_BUILD_VERSION)
    description: Binaries release
    draft: false
    prerelease: true
    auth_token:
      secure: F70O6SZTSCq38GRXMw0oflqtSR44IOm2uzzn417S4++VphBkgxGEY8mdG3cCxBBO
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
